---
name: "rabbitmq.aq.instance.create"
pack: "stackstorm_aqconsumer" 
description: "???"
enabled: true
trigger:
    type: stackstorm_send_notifications.aq_message

criteria:
    trigger.event_type:
        type: "iequals"
        pattern: "compute.instance.create.end"

action: ##not done yet
    ref: stackstorm_aqconsumer.instance.create
    parameters:
        message: "{{ trigger.message }}"